### ISSUE TITLE
Calva Formatter?

### ISSUE THREAD

**Issue by PEZ** [pesterhazy/cljs-corpus#2]
I am not sure how the indexing works, but think [Calva Formatter](https://github.com/BetterThanTomorrow/calva-fmt) (Extension for VS Code) would fit the list of applications written in ClojureScript.

Granted, it is a small extension, but anyway. :smile:

**Comment by pesterhazy** [comment]
Calva Formatter looks great! Have you considered shelling out to the new graalvm zprint binaries? I'm doing that with https://github.com/pesterhazy/zprint-mode.el/ and it's really fast.

As for cljs-corpus, I think Calva Formatter is too small to warrant inclusion

**Comment by PEZ** [comment]
Calva Formatter is written in ClojureScript, so it can use zprint as a library. (Today ut uses cljfmt, but I am considering offering zprint commands as well.) Seems like a bother to bundle binaries, but maybe there is a straight forward way to do it?
